# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3b9d4d45c71157cdfd9ab88635722e7967c7f4f95e15e58d6e943870f2033edfcf6ab8dc9fe8ac4d4315f29ec755791b0338ada63095ddb794037a7a371a1fcb

test:
  secret_key_base: dde6335845cd2a6c3e5dc508f813c5ed49011e1b3ef7f540b22894f3a6edd82dcab3a18ccdfe9cad348b5d3d64fa4c1857cecc01ac2d98bf42a77daa6ce722bd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
